# name: Deploy React App
# on: push
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get repository code
#         uses: actions/checkout@v4
#       - name : Install dependencies
#         run: npm ci
#       - name: Test application
#         run: npm run test
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get repository code
#         uses: actions/checkout@v3
#       - name : Install dependencies
#         run: npm ci
#       - name: Lint application
#         run: npm run lint
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get repository code
#         uses: actions/checkout@v3
#       - name : Install dependencies
#         run: npm ci
#       - name: Build application
#         run: npm run build
#       - name: Deploy
#         run: echo Deploying...

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
